// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhKUvf_oPKSSdh8L7PXB9ydQI21GJLvOI',
    appId: '1:340146495612:web:141182bc1676cf294a29f9',
    messagingSenderId: '340146495612',
    projectId: 'flutterdialogflow-2501c',
    authDomain: 'flutterdialogflow-2501c.firebaseapp.com',
    databaseURL: 'https://flutterdialogflow-2501c-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdialogflow-2501c.appspot.com',
    measurementId: 'G-P4JGCSSMHB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa-vVa5w7S406AYmx6dc8z3Hf8afXtb20',
    appId: '1:340146495612:ios:fdd034e5bedbf1464a29f9',
    messagingSenderId: '340146495612',
    projectId: 'flutterdialogflow-2501c',
    databaseURL: 'https://flutterdialogflow-2501c-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdialogflow-2501c.appspot.com',
    iosBundleId: 'com.example.flutterChatmateWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhKUvf_oPKSSdh8L7PXB9ydQI21GJLvOI',
    appId: '1:340146495612:web:36aff7eabd430eb94a29f9',
    messagingSenderId: '340146495612',
    projectId: 'flutterdialogflow-2501c',
    authDomain: 'flutterdialogflow-2501c.firebaseapp.com',
    databaseURL: 'https://flutterdialogflow-2501c-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdialogflow-2501c.appspot.com',
    measurementId: 'G-9RQ0E05LLL',
  );
}
